version: '2'

services:
  postgresql:
    image: 'postgres:10-alpine'
    volumes:
      - './postgresql_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  redmine:
    image: 'redmine:latest'
    ports:
      - '80:3000'
    environment:
      - REDMINE_DB_POSTGRES=postgresql
    volumes:
      - './redmine_data:/var/lib/redmine/default/files'
    depends_on:
      - postgresql
volumes:
  postgresql_data:
    driver: local
  redmine_data:
    driver: local